# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

  - name: About the lab
    url: '#About the lab'
    weight: 15
  
  - name: Research
    url: '#Research'
    weight: 20

  - name: Extension
    url: '#Extension'
    weight: 25

  - name: News
    url: '#News'
    weight: 30

  - name: Donors
    url: '#Donors'
    weight: 35

  - name: Educational program
    url: '#Educational program'
    weight: 40

  - name: Contact us
    url: '#Contact us'
    weight: 45

  - name: People
    url: '#Team'
    weight: 50

  - name: Publications
    url: '#publications'
    weight: 55   

